- name: Download and Install Jenkins Repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Download and install Jenkins Repo Key 
  rpm_key: 
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins Server
  action: yum name=jenkins state=installed

- name: Start and Enable Jenkins
  action: systemd name=jenkins state=restarted enabled=yes

- name: Sleep for 40 seconds and continue with play
  wait_for: timeout=40

- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
  tags:
    - jenkinspassword

- name: Print init password Jenkins
  debug:
    var: result.stdout
  tags:
    - jenkinspassword